name = "BAMF"
uuid = "b46b6485-dee9-4ab3-ae4f-5a975ad04c76"
authors = ["Keith A. Lidke <kalidke@users.noreply.github.com> and contributors"]
version = "0.1.0"

[deps]
ImageView = "86fae568-95e7-573e-a6b2-d8a6b900c9ef"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
